#!/usr/bin/env python
import os

from trex.support.run import Manager
from {NAME} import app

manager = Manager(app)

@manager.command
def compile_less():
    """ Compile less files
    """
    os.system("lessc {NAME}/cdn/less/app.less")

if __name__ == "__main__":
    manager.run()
