#!/usr/bin/env python

from trex.support.run import Manager
from {NAME} import app

manager = Manager(app)

@manager.command
def example():
    "Example manager command"

if __name__ == "__main__":
    manager.run()
